# Generated by Django 4.2.4 on 2023-08-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0011_book_user_followers_book_user_following_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_user',
            name='image',
            field=models.ImageField(default='images/default/photo-1511367461989-f85a21fda167.jpeg', upload_to='images/users'),
        ),
    ]
